services:
  mysql:
    image: mysql:8.0
    container_name: alizon_mysql
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/AlizonDB.sql:/docker-entrypoint-initdb.d/AlizonDB.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}

  php-apache:
    build:
      context: .
      dockerfile: php-server/Dockerfile
    container_name: alizon_php
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./css:/var/www/html/css
      - ./csv:/var/www/html/csv
      - ./download:/var/www/html/download
      - ./fonts:/var/www/html/fonts
      - ./img:/var/www/html/img
      - ./js:/var/www/html/js
    env_file:
      - .env

volumes:
  mysql_data:
